# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Z:\dev\stereoSurveys\stereoSurveysModule_dialog_base.ui'
#
# Created: Wed Jun 10 11:39:26 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_stereoSurveysDialogBase(object):
    def setupUi(self, stereoSurveysDialogBase):
        stereoSurveysDialogBase.setObjectName(_fromUtf8("stereoSurveysDialogBase"))
        stereoSurveysDialogBase.resize(1258, 272)
        self.horizontalLayout_4 = QtGui.QHBoxLayout(stereoSurveysDialogBase)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout_4.addItem(spacerItem)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem1 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.pushButtonSx = QtGui.QPushButton(stereoSurveysDialogBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSx.sizePolicy().hasHeightForWidth())
        self.pushButtonSx.setSizePolicy(sizePolicy)
        self.pushButtonSx.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButtonSx.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButtonSx.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/stereoSurveys/lib/viewpointSx.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonSx.setIcon(icon)
        self.pushButtonSx.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonSx.setObjectName(_fromUtf8("pushButtonSx"))
        self.horizontalLayout_2.addWidget(self.pushButtonSx)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.labelLonSx = QtGui.QLabel(stereoSurveysDialogBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLonSx.sizePolicy().hasHeightForWidth())
        self.labelLonSx.setSizePolicy(sizePolicy)
        self.labelLonSx.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelLonSx.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelLonSx.setObjectName(_fromUtf8("labelLonSx"))
        self.verticalLayout_6.addWidget(self.labelLonSx)
        self.labelLatSx = QtGui.QLabel(stereoSurveysDialogBase)
        self.labelLatSx.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelLatSx.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelLatSx.setObjectName(_fromUtf8("labelLatSx"))
        self.verticalLayout_6.addWidget(self.labelLatSx)
        self.labelHeadingSx = QtGui.QLabel(stereoSurveysDialogBase)
        self.labelHeadingSx.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelHeadingSx.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelHeadingSx.setObjectName(_fromUtf8("labelHeadingSx"))
        self.verticalLayout_6.addWidget(self.labelHeadingSx)
        self.labelPhotoHeadingSx = QtGui.QLabel(stereoSurveysDialogBase)
        self.labelPhotoHeadingSx.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelPhotoHeadingSx.setTextFormat(QtCore.Qt.AutoText)
        self.labelPhotoHeadingSx.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelPhotoHeadingSx.setObjectName(_fromUtf8("labelPhotoHeadingSx"))
        self.verticalLayout_6.addWidget(self.labelPhotoHeadingSx)
        self.correzioneSx = QtGui.QLineEdit(stereoSurveysDialogBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.correzioneSx.sizePolicy().hasHeightForWidth())
        self.correzioneSx.setSizePolicy(sizePolicy)
        self.correzioneSx.setMinimumSize(QtCore.QSize(50, 0))
        self.correzioneSx.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.correzioneSx.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.correzioneSx.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.correzioneSx.setObjectName(_fromUtf8("correzioneSx"))
        self.verticalLayout_6.addWidget(self.correzioneSx)
        self.verticalLayout_3.addLayout(self.verticalLayout_6)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.webViewSx = QtWebKit.QWebView(stereoSurveysDialogBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.webViewSx.sizePolicy().hasHeightForWidth())
        self.webViewSx.setSizePolicy(sizePolicy)
        self.webViewSx.setMinimumSize(QtCore.QSize(400, 250))
        self.webViewSx.setMaximumSize(QtCore.QSize(400, 250))
        self.webViewSx.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.webViewSx.setObjectName(_fromUtf8("webViewSx"))
        self.verticalLayout_2.addWidget(self.webViewSx, QtCore.Qt.AlignTop)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame = QtGui.QFrame(stereoSurveysDialogBase)
        self.frame.setMinimumSize(QtCore.QSize(150, 150))
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 150, 150))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/stereoSurveys/lib/cross.png")))
        self.label.setObjectName(_fromUtf8("label"))
        self.webViewPlan = QtWebKit.QWebView(self.frame)
        self.webViewPlan.setGeometry(QtCore.QRect(0, 0, 150, 150))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.webViewPlan.sizePolicy().hasHeightForWidth())
        self.webViewPlan.setSizePolicy(sizePolicy)
        self.webViewPlan.setMinimumSize(QtCore.QSize(150, 150))
        self.webViewPlan.setMaximumSize(QtCore.QSize(150, 150))
        self.webViewPlan.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.webViewPlan.setObjectName(_fromUtf8("webViewPlan"))
        self.verticalLayout.addWidget(self.frame)
        spacerItem4 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.labelLon = QtGui.QLabel(stereoSurveysDialogBase)
        self.labelLon.setObjectName(_fromUtf8("labelLon"))
        self.verticalLayout.addWidget(self.labelLon)
        self.labelLat = QtGui.QLabel(stereoSurveysDialogBase)
        self.labelLat.setObjectName(_fromUtf8("labelLat"))
        self.verticalLayout.addWidget(self.labelLat)
        self.labelX = QtGui.QLabel(stereoSurveysDialogBase)
        self.labelX.setObjectName(_fromUtf8("labelX"))
        self.verticalLayout.addWidget(self.labelX)
        self.labelY = QtGui.QLabel(stereoSurveysDialogBase)
        self.labelY.setObjectName(_fromUtf8("labelY"))
        self.verticalLayout.addWidget(self.labelY)
        self.pushButton = QtGui.QPushButton(stereoSurveysDialogBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(150, 0))
        self.pushButton.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout.addWidget(self.pushButton)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.webViewDx = QtWebKit.QWebView(stereoSurveysDialogBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.webViewDx.sizePolicy().hasHeightForWidth())
        self.webViewDx.setSizePolicy(sizePolicy)
        self.webViewDx.setMinimumSize(QtCore.QSize(400, 250))
        self.webViewDx.setMaximumSize(QtCore.QSize(400, 250))
        self.webViewDx.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.webViewDx.setObjectName(_fromUtf8("webViewDx"))
        self.verticalLayout_4.addWidget(self.webViewDx, QtCore.Qt.AlignTop)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushButtonDx = QtGui.QPushButton(stereoSurveysDialogBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonDx.sizePolicy().hasHeightForWidth())
        self.pushButtonDx.setSizePolicy(sizePolicy)
        self.pushButtonDx.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButtonDx.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButtonDx.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/stereoSurveys/lib/viewpointDx.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonDx.setIcon(icon1)
        self.pushButtonDx.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonDx.setObjectName(_fromUtf8("pushButtonDx"))
        self.horizontalLayout_3.addWidget(self.pushButtonDx)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem6)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.labelLonDx = QtGui.QLabel(stereoSurveysDialogBase)
        self.labelLonDx.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelLonDx.setObjectName(_fromUtf8("labelLonDx"))
        self.verticalLayout_7.addWidget(self.labelLonDx)
        self.labelLatDx = QtGui.QLabel(stereoSurveysDialogBase)
        self.labelLatDx.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelLatDx.setObjectName(_fromUtf8("labelLatDx"))
        self.verticalLayout_7.addWidget(self.labelLatDx)
        self.labelHeadingDx = QtGui.QLabel(stereoSurveysDialogBase)
        self.labelHeadingDx.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelHeadingDx.setObjectName(_fromUtf8("labelHeadingDx"))
        self.verticalLayout_7.addWidget(self.labelHeadingDx)
        self.labelPhotoHeadingDx = QtGui.QLabel(stereoSurveysDialogBase)
        self.labelPhotoHeadingDx.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelPhotoHeadingDx.setTextFormat(QtCore.Qt.AutoText)
        self.labelPhotoHeadingDx.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelPhotoHeadingDx.setObjectName(_fromUtf8("labelPhotoHeadingDx"))
        self.verticalLayout_7.addWidget(self.labelPhotoHeadingDx)
        self.correzioneDx = QtGui.QLineEdit(stereoSurveysDialogBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.correzioneDx.sizePolicy().hasHeightForWidth())
        self.correzioneDx.setSizePolicy(sizePolicy)
        self.correzioneDx.setMinimumSize(QtCore.QSize(0, 0))
        self.correzioneDx.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.correzioneDx.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.correzioneDx.setObjectName(_fromUtf8("correzioneDx"))
        self.verticalLayout_7.addWidget(self.correzioneDx)
        self.verticalLayout_5.addLayout(self.verticalLayout_7)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        spacerItem7 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)

        self.retranslateUi(stereoSurveysDialogBase)
        QtCore.QMetaObject.connectSlotsByName(stereoSurveysDialogBase)

    def retranslateUi(self, stereoSurveysDialogBase):
        stereoSurveysDialogBase.setWindowTitle(_translate("stereoSurveysDialogBase", "visual surveys", None))
        self.labelLonSx.setText(_translate("stereoSurveysDialogBase", "lonsx", None))
        self.labelLatSx.setText(_translate("stereoSurveysDialogBase", "latsx", None))
        self.labelHeadingSx.setText(_translate("stereoSurveysDialogBase", "headSx", None))
        self.labelPhotoHeadingSx.setText(_translate("stereoSurveysDialogBase", "photoSx", None))
        self.correzioneSx.setText(_translate("stereoSurveysDialogBase", "0", None))
        self.labelLon.setText(_translate("stereoSurveysDialogBase", "lon", None))
        self.labelLat.setText(_translate("stereoSurveysDialogBase", "lat", None))
        self.labelX.setText(_translate("stereoSurveysDialogBase", "X", None))
        self.labelY.setText(_translate("stereoSurveysDialogBase", "Y", None))
        self.pushButton.setText(_translate("stereoSurveysDialogBase", "Digitize on map", None))
        self.labelLonDx.setText(_translate("stereoSurveysDialogBase", "londx", None))
        self.labelLatDx.setText(_translate("stereoSurveysDialogBase", "latdx", None))
        self.labelHeadingDx.setText(_translate("stereoSurveysDialogBase", "headdx", None))
        self.labelPhotoHeadingDx.setText(_translate("stereoSurveysDialogBase", "photodx", None))
        self.correzioneDx.setText(_translate("stereoSurveysDialogBase", "0", None))

from PyQt4 import QtWebKit
import resources_rc
