# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/enrico/Dropbox/dev/stereoSurveys/stereoSurveysModule_dialog_base.ui'
#
# Created: Mon Jul 20 21:34:59 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_stereoSurveysDialogBase(object):
    def setupUi(self, stereoSurveysDialogBase):
        stereoSurveysDialogBase.setObjectName(_fromUtf8("stereoSurveysDialogBase"))
        stereoSurveysDialogBase.resize(1355, 305)
        self.verticalLayout_11 = QtGui.QVBoxLayout(stereoSurveysDialogBase)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButtonSx = QtGui.QPushButton(stereoSurveysDialogBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSx.sizePolicy().hasHeightForWidth())
        self.pushButtonSx.setSizePolicy(sizePolicy)
        self.pushButtonSx.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButtonSx.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButtonSx.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/stereoSurveys/lib/viewpointSx.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonSx.setIcon(icon)
        self.pushButtonSx.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonSx.setObjectName(_fromUtf8("pushButtonSx"))
        self.horizontalLayout_2.addWidget(self.pushButtonSx)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(2)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem3 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setSpacing(1)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_16 = QtGui.QLabel(stereoSurveysDialogBase)
        self.label_16.setMinimumSize(QtCore.QSize(30, 0))
        self.label_16.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_10.addWidget(self.label_16)
        self.label_8 = QtGui.QLabel(stereoSurveysDialogBase)
        self.label_8.setMinimumSize(QtCore.QSize(30, 0))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_10.addWidget(self.label_8)
        self.label_9 = QtGui.QLabel(stereoSurveysDialogBase)
        self.label_9.setMinimumSize(QtCore.QSize(30, 0))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_10.addWidget(self.label_9)
        self.label_10 = QtGui.QLabel(stereoSurveysDialogBase)
        self.label_10.setMinimumSize(QtCore.QSize(30, 0))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_10.addWidget(self.label_10)
        self.label_11 = QtGui.QLabel(stereoSurveysDialogBase)
        self.label_11.setMinimumSize(QtCore.QSize(30, 0))
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_10.addWidget(self.label_11)
        self.label_12 = QtGui.QLabel(stereoSurveysDialogBase)
        self.label_12.setMinimumSize(QtCore.QSize(30, 0))
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_10.addWidget(self.label_12)
        self.label_13 = QtGui.QLabel(stereoSurveysDialogBase)
        self.label_13.setMinimumSize(QtCore.QSize(30, 0))
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_10.addWidget(self.label_13)
        self.label_14 = QtGui.QLabel(stereoSurveysDialogBase)
        self.label_14.setMinimumSize(QtCore.QSize(30, 0))
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_10.addWidget(self.label_14)
        self.label_15 = QtGui.QLabel(stereoSurveysDialogBase)
        self.label_15.setMinimumSize(QtCore.QSize(30, 0))
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_10.addWidget(self.label_15)
        self.label_18 = QtGui.QLabel(stereoSurveysDialogBase)
        self.label_18.setMinimumSize(QtCore.QSize(35, 25))
        self.label_18.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_10.addWidget(self.label_18)
        self.horizontalLayout_5.addLayout(self.verticalLayout_10)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setSpacing(1)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_17 = QtGui.QLabel(stereoSurveysDialogBase)
        self.label_17.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_6.addWidget(self.label_17)
        self.labelLonSx = QtGui.QLabel(stereoSurveysDialogBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLonSx.sizePolicy().hasHeightForWidth())
        self.labelLonSx.setSizePolicy(sizePolicy)
        self.labelLonSx.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelLonSx.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelLonSx.setObjectName(_fromUtf8("labelLonSx"))
        self.verticalLayout_6.addWidget(self.labelLonSx)
        self.labelLatSx = QtGui.QLabel(stereoSurveysDialogBase)
        self.labelLatSx.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelLatSx.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelLatSx.setObjectName(_fromUtf8("labelLatSx"))
        self.verticalLayout_6.addWidget(self.labelLatSx)
        self.labelHeadingSx = QtGui.QLabel(stereoSurveysDialogBase)
        self.labelHeadingSx.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelHeadingSx.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelHeadingSx.setObjectName(_fromUtf8("labelHeadingSx"))
        self.verticalLayout_6.addWidget(self.labelHeadingSx)
        self.labelPhotoHeadingSx = QtGui.QLabel(stereoSurveysDialogBase)
        self.labelPhotoHeadingSx.setEnabled(True)
        self.labelPhotoHeadingSx.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelPhotoHeadingSx.setTextFormat(QtCore.Qt.AutoText)
        self.labelPhotoHeadingSx.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelPhotoHeadingSx.setObjectName(_fromUtf8("labelPhotoHeadingSx"))
        self.verticalLayout_6.addWidget(self.labelPhotoHeadingSx)
        self.labelPitchSx = QtGui.QLabel(stereoSurveysDialogBase)
        self.labelPitchSx.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelPitchSx.setObjectName(_fromUtf8("labelPitchSx"))
        self.verticalLayout_6.addWidget(self.labelPitchSx)
        self.labelDistSx = QtGui.QLabel(stereoSurveysDialogBase)
        self.labelDistSx.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelDistSx.setObjectName(_fromUtf8("labelDistSx"))
        self.verticalLayout_6.addWidget(self.labelDistSx)
        self.labelHeightSx = QtGui.QLabel(stereoSurveysDialogBase)
        self.labelHeightSx.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelHeightSx.setObjectName(_fromUtf8("labelHeightSx"))
        self.verticalLayout_6.addWidget(self.labelHeightSx)
        self.labelCalibrationSx = QtGui.QLabel(stereoSurveysDialogBase)
        self.labelCalibrationSx.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelCalibrationSx.setObjectName(_fromUtf8("labelCalibrationSx"))
        self.verticalLayout_6.addWidget(self.labelCalibrationSx)
        self.googleCameraHeightSx = QtGui.QLineEdit(stereoSurveysDialogBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.googleCameraHeightSx.sizePolicy().hasHeightForWidth())
        self.googleCameraHeightSx.setSizePolicy(sizePolicy)
        self.googleCameraHeightSx.setMinimumSize(QtCore.QSize(20, 0))
        self.googleCameraHeightSx.setMaximumSize(QtCore.QSize(55, 16777215))
        self.googleCameraHeightSx.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.googleCameraHeightSx.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.googleCameraHeightSx.setObjectName(_fromUtf8("googleCameraHeightSx"))
        self.verticalLayout_6.addWidget(self.googleCameraHeightSx)
        self.horizontalLayout_5.addLayout(self.verticalLayout_6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.correzioneSx = QtGui.QLineEdit(stereoSurveysDialogBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.correzioneSx.sizePolicy().hasHeightForWidth())
        self.correzioneSx.setSizePolicy(sizePolicy)
        self.correzioneSx.setMinimumSize(QtCore.QSize(0, 0))
        self.correzioneSx.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.correzioneSx.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.correzioneSx.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.correzioneSx.setObjectName(_fromUtf8("correzioneSx"))
        self.verticalLayout_3.addWidget(self.correzioneSx)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.webViewSx = QtWebKit.QWebView(stereoSurveysDialogBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.webViewSx.sizePolicy().hasHeightForWidth())
        self.webViewSx.setSizePolicy(sizePolicy)
        self.webViewSx.setMinimumSize(QtCore.QSize(400, 260))
        self.webViewSx.setMaximumSize(QtCore.QSize(400, 260))
        self.webViewSx.setProperty("url", QtCore.QUrl(_fromUtf8("about:blank")))
        self.webViewSx.setObjectName(_fromUtf8("webViewSx"))
        self.verticalLayout_2.addWidget(self.webViewSx)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame = QtGui.QFrame(stereoSurveysDialogBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(150, 150))
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.webViewPlan = QtWebKit.QWebView(self.frame)
        self.webViewPlan.setGeometry(QtCore.QRect(0, 0, 150, 150))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.webViewPlan.sizePolicy().hasHeightForWidth())
        self.webViewPlan.setSizePolicy(sizePolicy)
        self.webViewPlan.setMinimumSize(QtCore.QSize(150, 150))
        self.webViewPlan.setMaximumSize(QtCore.QSize(150, 150))
        self.webViewPlan.setProperty("url", QtCore.QUrl(_fromUtf8("about:blank")))
        self.webViewPlan.setObjectName(_fromUtf8("webViewPlan"))
        self.verticalLayout.addWidget(self.frame)
        spacerItem4 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setSpacing(2)
        self.verticalLayout_13.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_4 = QtGui.QLabel(stereoSurveysDialogBase)
        self.label_4.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_8.addWidget(self.label_4)
        self.label = QtGui.QLabel(stereoSurveysDialogBase)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_8.addWidget(self.label)
        self.label_6 = QtGui.QLabel(stereoSurveysDialogBase)
        self.label_6.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_8.addWidget(self.label_6)
        self.label_7 = QtGui.QLabel(stereoSurveysDialogBase)
        self.label_7.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_8.addWidget(self.label_7)
        self.labelX_2 = QtGui.QLabel(stereoSurveysDialogBase)
        self.labelX_2.setMaximumSize(QtCore.QSize(20, 16777215))
        self.labelX_2.setObjectName(_fromUtf8("labelX_2"))
        self.verticalLayout_8.addWidget(self.labelX_2)
        self.labelY_2 = QtGui.QLabel(stereoSurveysDialogBase)
        self.labelY_2.setMaximumSize(QtCore.QSize(20, 16777215))
        self.labelY_2.setObjectName(_fromUtf8("labelY_2"))
        self.verticalLayout_8.addWidget(self.labelY_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.labelMeanHeight = QtGui.QLabel(stereoSurveysDialogBase)
        self.labelMeanHeight.setMinimumSize(QtCore.QSize(120, 0))
        self.labelMeanHeight.setObjectName(_fromUtf8("labelMeanHeight"))
        self.verticalLayout_9.addWidget(self.labelMeanHeight)
        self.labelMeanHeightError = QtGui.QLabel(stereoSurveysDialogBase)
        self.labelMeanHeightError.setObjectName(_fromUtf8("labelMeanHeightError"))
        self.verticalLayout_9.addWidget(self.labelMeanHeightError)
        self.labelLon = QtGui.QLabel(stereoSurveysDialogBase)
        self.labelLon.setMinimumSize(QtCore.QSize(100, 0))
        self.labelLon.setObjectName(_fromUtf8("labelLon"))
        self.verticalLayout_9.addWidget(self.labelLon)
        self.labelLat = QtGui.QLabel(stereoSurveysDialogBase)
        self.labelLat.setMinimumSize(QtCore.QSize(100, 0))
        self.labelLat.setObjectName(_fromUtf8("labelLat"))
        self.verticalLayout_9.addWidget(self.labelLat)
        self.labelX = QtGui.QLabel(stereoSurveysDialogBase)
        self.labelX.setMinimumSize(QtCore.QSize(100, 0))
        self.labelX.setObjectName(_fromUtf8("labelX"))
        self.verticalLayout_9.addWidget(self.labelX)
        self.labelY = QtGui.QLabel(stereoSurveysDialogBase)
        self.labelY.setMinimumSize(QtCore.QSize(100, 0))
        self.labelY.setObjectName(_fromUtf8("labelY"))
        self.verticalLayout_9.addWidget(self.labelY)
        self.horizontalLayout_4.addLayout(self.verticalLayout_9)
        self.verticalLayout_13.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.objNameSlot = QtGui.QLineEdit(stereoSurveysDialogBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.objNameSlot.sizePolicy().hasHeightForWidth())
        self.objNameSlot.setSizePolicy(sizePolicy)
        self.objNameSlot.setMinimumSize(QtCore.QSize(0, 0))
        self.objNameSlot.setMaximumSize(QtCore.QSize(70, 16777215))
        self.objNameSlot.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.objNameSlot.setText(_fromUtf8(""))
        self.objNameSlot.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.objNameSlot.setObjectName(_fromUtf8("objNameSlot"))
        self.horizontalLayout_10.addWidget(self.objNameSlot)
        self.pushButton = QtGui.QPushButton(stereoSurveysDialogBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout_10.addWidget(self.pushButton)
        self.verticalLayout_13.addLayout(self.horizontalLayout_10)
        self.verticalLayout.addLayout(self.verticalLayout_13)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.webViewDx = QtWebKit.QWebView(stereoSurveysDialogBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.webViewDx.sizePolicy().hasHeightForWidth())
        self.webViewDx.setSizePolicy(sizePolicy)
        self.webViewDx.setMinimumSize(QtCore.QSize(400, 260))
        self.webViewDx.setMaximumSize(QtCore.QSize(400, 260))
        self.webViewDx.setProperty("url", QtCore.QUrl(_fromUtf8("about:blank")))
        self.webViewDx.setObjectName(_fromUtf8("webViewDx"))
        self.verticalLayout_4.addWidget(self.webViewDx)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.pushButtonDx = QtGui.QPushButton(stereoSurveysDialogBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonDx.sizePolicy().hasHeightForWidth())
        self.pushButtonDx.setSizePolicy(sizePolicy)
        self.pushButtonDx.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButtonDx.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButtonDx.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/stereoSurveys/lib/viewpointDx.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonDx.setIcon(icon1)
        self.pushButtonDx.setIconSize(QtCore.QSize(24, 24))
        self.pushButtonDx.setObjectName(_fromUtf8("pushButtonDx"))
        self.horizontalLayout_3.addWidget(self.pushButtonDx)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(2)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setSpacing(1)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_19 = QtGui.QLabel(stereoSurveysDialogBase)
        self.label_19.setMinimumSize(QtCore.QSize(35, 0))
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_12.addWidget(self.label_19)
        self.label_20 = QtGui.QLabel(stereoSurveysDialogBase)
        self.label_20.setMinimumSize(QtCore.QSize(35, 0))
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_12.addWidget(self.label_20)
        self.label_21 = QtGui.QLabel(stereoSurveysDialogBase)
        self.label_21.setMinimumSize(QtCore.QSize(35, 0))
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout_12.addWidget(self.label_21)
        self.label_22 = QtGui.QLabel(stereoSurveysDialogBase)
        self.label_22.setMinimumSize(QtCore.QSize(35, 0))
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.verticalLayout_12.addWidget(self.label_22)
        self.label_23 = QtGui.QLabel(stereoSurveysDialogBase)
        self.label_23.setMinimumSize(QtCore.QSize(35, 0))
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.verticalLayout_12.addWidget(self.label_23)
        self.label_24 = QtGui.QLabel(stereoSurveysDialogBase)
        self.label_24.setMinimumSize(QtCore.QSize(35, 0))
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.verticalLayout_12.addWidget(self.label_24)
        self.label_25 = QtGui.QLabel(stereoSurveysDialogBase)
        self.label_25.setMinimumSize(QtCore.QSize(35, 0))
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.verticalLayout_12.addWidget(self.label_25)
        self.label_26 = QtGui.QLabel(stereoSurveysDialogBase)
        self.label_26.setMinimumSize(QtCore.QSize(35, 0))
        self.label_26.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.verticalLayout_12.addWidget(self.label_26)
        self.label_27 = QtGui.QLabel(stereoSurveysDialogBase)
        self.label_27.setMinimumSize(QtCore.QSize(35, 0))
        self.label_27.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.verticalLayout_12.addWidget(self.label_27)
        self.label_28 = QtGui.QLabel(stereoSurveysDialogBase)
        self.label_28.setMinimumSize(QtCore.QSize(0, 25))
        self.label_28.setMaximumSize(QtCore.QSize(35, 16777215))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.verticalLayout_12.addWidget(self.label_28)
        self.horizontalLayout_7.addLayout(self.verticalLayout_12)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setSpacing(1)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_29 = QtGui.QLabel(stereoSurveysDialogBase)
        self.label_29.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.verticalLayout_7.addWidget(self.label_29)
        self.labelLonDx = QtGui.QLabel(stereoSurveysDialogBase)
        self.labelLonDx.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelLonDx.setObjectName(_fromUtf8("labelLonDx"))
        self.verticalLayout_7.addWidget(self.labelLonDx)
        self.labelLatDx = QtGui.QLabel(stereoSurveysDialogBase)
        self.labelLatDx.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelLatDx.setObjectName(_fromUtf8("labelLatDx"))
        self.verticalLayout_7.addWidget(self.labelLatDx)
        self.labelHeadingDx = QtGui.QLabel(stereoSurveysDialogBase)
        self.labelHeadingDx.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelHeadingDx.setObjectName(_fromUtf8("labelHeadingDx"))
        self.verticalLayout_7.addWidget(self.labelHeadingDx)
        self.labelPhotoHeadingDx = QtGui.QLabel(stereoSurveysDialogBase)
        self.labelPhotoHeadingDx.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelPhotoHeadingDx.setTextFormat(QtCore.Qt.AutoText)
        self.labelPhotoHeadingDx.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelPhotoHeadingDx.setObjectName(_fromUtf8("labelPhotoHeadingDx"))
        self.verticalLayout_7.addWidget(self.labelPhotoHeadingDx)
        self.labelPitchDx = QtGui.QLabel(stereoSurveysDialogBase)
        self.labelPitchDx.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelPitchDx.setObjectName(_fromUtf8("labelPitchDx"))
        self.verticalLayout_7.addWidget(self.labelPitchDx)
        self.labelDistDx = QtGui.QLabel(stereoSurveysDialogBase)
        self.labelDistDx.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelDistDx.setObjectName(_fromUtf8("labelDistDx"))
        self.verticalLayout_7.addWidget(self.labelDistDx)
        self.labelHeightDx = QtGui.QLabel(stereoSurveysDialogBase)
        self.labelHeightDx.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelHeightDx.setObjectName(_fromUtf8("labelHeightDx"))
        self.verticalLayout_7.addWidget(self.labelHeightDx)
        self.labelCalibrationDx = QtGui.QLabel(stereoSurveysDialogBase)
        self.labelCalibrationDx.setObjectName(_fromUtf8("labelCalibrationDx"))
        self.verticalLayout_7.addWidget(self.labelCalibrationDx)
        self.googleCameraHeightDx = QtGui.QLineEdit(stereoSurveysDialogBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.googleCameraHeightDx.sizePolicy().hasHeightForWidth())
        self.googleCameraHeightDx.setSizePolicy(sizePolicy)
        self.googleCameraHeightDx.setMinimumSize(QtCore.QSize(20, 0))
        self.googleCameraHeightDx.setMaximumSize(QtCore.QSize(55, 16777215))
        self.googleCameraHeightDx.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.googleCameraHeightDx.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.googleCameraHeightDx.setObjectName(_fromUtf8("googleCameraHeightDx"))
        self.verticalLayout_7.addWidget(self.googleCameraHeightDx)
        self.horizontalLayout_7.addLayout(self.verticalLayout_7)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.correzioneDx = QtGui.QLineEdit(stereoSurveysDialogBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.correzioneDx.sizePolicy().hasHeightForWidth())
        self.correzioneDx.setSizePolicy(sizePolicy)
        self.correzioneDx.setMinimumSize(QtCore.QSize(0, 0))
        self.correzioneDx.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.correzioneDx.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.correzioneDx.setObjectName(_fromUtf8("correzioneDx"))
        self.verticalLayout_5.addWidget(self.correzioneDx)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        spacerItem8 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.verticalLayout_11.addLayout(self.horizontalLayout)
        spacerItem9 = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem9)

        self.retranslateUi(stereoSurveysDialogBase)
        QtCore.QMetaObject.connectSlotsByName(stereoSurveysDialogBase)

    def retranslateUi(self, stereoSurveysDialogBase):
        stereoSurveysDialogBase.setWindowTitle(_translate("stereoSurveysDialogBase", "visual surveys", None))
        self.label_16.setText(_translate("stereoSurveysDialogBase", "Left", None))
        self.label_8.setText(_translate("stereoSurveysDialogBase", "Lon:", None))
        self.label_9.setText(_translate("stereoSurveysDialogBase", "Lat:", None))
        self.label_10.setText(_translate("stereoSurveysDialogBase", "Head:", None))
        self.label_11.setText(_translate("stereoSurveysDialogBase", "Shot:", None))
        self.label_12.setText(_translate("stereoSurveysDialogBase", "Pitch:", None))
        self.label_13.setText(_translate("stereoSurveysDialogBase", "Dist:", None))
        self.label_14.setText(_translate("stereoSurveysDialogBase", "H:", None))
        self.label_15.setText(_translate("stereoSurveysDialogBase", "Cal:", None))
        self.label_18.setText(_translate("stereoSurveysDialogBase", "Hcam:", None))
        self.label_17.setText(_translate("stereoSurveysDialogBase", "camera", None))
        self.labelLonSx.setToolTip(_translate("stereoSurveysDialogBase", "longitude", None))
        self.labelLonSx.setText(_translate("stereoSurveysDialogBase", "lonsx", None))
        self.labelLatSx.setToolTip(_translate("stereoSurveysDialogBase", "latitude", None))
        self.labelLatSx.setText(_translate("stereoSurveysDialogBase", "latsx", None))
        self.labelHeadingSx.setToolTip(_translate("stereoSurveysDialogBase", "heading", None))
        self.labelHeadingSx.setText(_translate("stereoSurveysDialogBase", "headSx", None))
        self.labelPhotoHeadingSx.setToolTip(_translate("stereoSurveysDialogBase", "photo heading", None))
        self.labelPhotoHeadingSx.setText(_translate("stereoSurveysDialogBase", "photoSx", None))
        self.labelPitchSx.setToolTip(_translate("stereoSurveysDialogBase", "pitch angle on horizon", None))
        self.labelPitchSx.setText(_translate("stereoSurveysDialogBase", "pitchSx", None))
        self.labelDistSx.setToolTip(_translate("stereoSurveysDialogBase", "distance from measurement point", None))
        self.labelDistSx.setStatusTip(_translate("stereoSurveysDialogBase", "distance from measurement point", None))
        self.labelDistSx.setText(_translate("stereoSurveysDialogBase", "distSx", None))
        self.labelHeightSx.setToolTip(_translate("stereoSurveysDialogBase", "height of measurement", None))
        self.labelHeightSx.setText(_translate("stereoSurveysDialogBase", "heightSx", None))
        self.labelCalibrationSx.setToolTip(_translate("stereoSurveysDialogBase", "calibration value", None))
        self.labelCalibrationSx.setText(_translate("stereoSurveysDialogBase", "calibrationSx", None))
        self.googleCameraHeightSx.setToolTip(_translate("stereoSurveysDialogBase", "google camera height", None))
        self.googleCameraHeightSx.setText(_translate("stereoSurveysDialogBase", "2.5", None))
        self.correzioneSx.setToolTip(_translate("stereoSurveysDialogBase", "user correction value", None))
        self.correzioneSx.setText(_translate("stereoSurveysDialogBase", "0", None))
        self.label_4.setText(_translate("stereoSurveysDialogBase", "H:", None))
        self.label.setText(_translate("stereoSurveysDialogBase", "+/-", None))
        self.label_6.setText(_translate("stereoSurveysDialogBase", "Lon:", None))
        self.label_7.setText(_translate("stereoSurveysDialogBase", "Lat:", None))
        self.labelX_2.setToolTip(_translate("stereoSurveysDialogBase", "coordinate X  of measurement", None))
        self.labelX_2.setText(_translate("stereoSurveysDialogBase", "X:", None))
        self.labelY_2.setToolTip(_translate("stereoSurveysDialogBase", "coordinate Y  of measurement", None))
        self.labelY_2.setText(_translate("stereoSurveysDialogBase", "Y:", None))
        self.labelMeanHeight.setToolTip(_translate("stereoSurveysDialogBase", "mean height", None))
        self.labelMeanHeight.setText(_translate("stereoSurveysDialogBase", "meanHeight", None))
        self.labelMeanHeightError.setText(_translate("stereoSurveysDialogBase", "meanHeightError", None))
        self.labelLon.setToolTip(_translate("stereoSurveysDialogBase", "longitude of measurement", None))
        self.labelLon.setText(_translate("stereoSurveysDialogBase", "lon", None))
        self.labelLat.setToolTip(_translate("stereoSurveysDialogBase", "latitude  of measurement", None))
        self.labelLat.setText(_translate("stereoSurveysDialogBase", "lat", None))
        self.labelX.setToolTip(_translate("stereoSurveysDialogBase", "coordinate X  of measurement", None))
        self.labelX.setText(_translate("stereoSurveysDialogBase", "X", None))
        self.labelY.setToolTip(_translate("stereoSurveysDialogBase", "coordinate Y  of measurement", None))
        self.labelY.setText(_translate("stereoSurveysDialogBase", "Y", None))
        self.objNameSlot.setToolTip(_translate("stereoSurveysDialogBase", "object measurement label", None))
        self.objNameSlot.setStatusTip(_translate("stereoSurveysDialogBase", "Object measurent label", None))
        self.pushButton.setText(_translate("stereoSurveysDialogBase", "Digitize", None))
        self.pushButtonDx.setToolTip(_translate("stereoSurveysDialogBase", "locate right panorama on map", None))
        self.label_19.setText(_translate("stereoSurveysDialogBase", "Right", None))
        self.label_20.setText(_translate("stereoSurveysDialogBase", "Lon:", None))
        self.label_21.setText(_translate("stereoSurveysDialogBase", "Lat:", None))
        self.label_22.setText(_translate("stereoSurveysDialogBase", "Head:", None))
        self.label_23.setText(_translate("stereoSurveysDialogBase", "Shot:", None))
        self.label_24.setText(_translate("stereoSurveysDialogBase", "Pitch:", None))
        self.label_25.setText(_translate("stereoSurveysDialogBase", "Dist:", None))
        self.label_26.setText(_translate("stereoSurveysDialogBase", "H:", None))
        self.label_27.setText(_translate("stereoSurveysDialogBase", "Cal:", None))
        self.label_28.setText(_translate("stereoSurveysDialogBase", "Hcam:", None))
        self.label_29.setText(_translate("stereoSurveysDialogBase", "camera", None))
        self.labelLonDx.setToolTip(_translate("stereoSurveysDialogBase", "longitude", None))
        self.labelLonDx.setText(_translate("stereoSurveysDialogBase", "londx", None))
        self.labelLatDx.setToolTip(_translate("stereoSurveysDialogBase", "latitude", None))
        self.labelLatDx.setText(_translate("stereoSurveysDialogBase", "latdx", None))
        self.labelHeadingDx.setToolTip(_translate("stereoSurveysDialogBase", "heading", None))
        self.labelHeadingDx.setText(_translate("stereoSurveysDialogBase", "headdx", None))
        self.labelPhotoHeadingDx.setToolTip(_translate("stereoSurveysDialogBase", "photo heading", None))
        self.labelPhotoHeadingDx.setText(_translate("stereoSurveysDialogBase", "photodx", None))
        self.labelPitchDx.setToolTip(_translate("stereoSurveysDialogBase", "pitch angle of camera", None))
        self.labelPitchDx.setText(_translate("stereoSurveysDialogBase", "pitchDx", None))
        self.labelDistDx.setToolTip(_translate("stereoSurveysDialogBase", "distance from measurement point", None))
        self.labelDistDx.setStatusTip(_translate("stereoSurveysDialogBase", "distance from measurement point", None))
        self.labelDistDx.setText(_translate("stereoSurveysDialogBase", "distDx", None))
        self.labelHeightDx.setToolTip(_translate("stereoSurveysDialogBase", "height of measurement", None))
        self.labelHeightDx.setText(_translate("stereoSurveysDialogBase", "heightDx", None))
        self.labelCalibrationDx.setToolTip(_translate("stereoSurveysDialogBase", "calibration value", None))
        self.labelCalibrationDx.setText(_translate("stereoSurveysDialogBase", "calibrationDx", None))
        self.googleCameraHeightDx.setToolTip(_translate("stereoSurveysDialogBase", "google camera height", None))
        self.googleCameraHeightDx.setText(_translate("stereoSurveysDialogBase", "2.5", None))
        self.correzioneDx.setToolTip(_translate("stereoSurveysDialogBase", "correction value", None))
        self.correzioneDx.setText(_translate("stereoSurveysDialogBase", "0", None))

from PyQt4 import QtWebKit
import resources_rc
